### ISSUE TITLE
ErrorHandler crashes with Protocol.UndefinedError in format_stack/1

### ISSUE THREAD

**Issue by arjan** [appsignal/appsignal-elixir#157]
```
14:52:32.505 [error] GenEvent handler Appsignal.ErrorHandler installed in :error_logger terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {GenServer, :call, [#PID<0.2398.0>, {:prepare_checkout, :web, #PID<0.2396.0>}, 5000]}
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1776: Enum.reduce/3
    (appsignal) lib/appsignal/error_handler.ex:150: Appsignal.ErrorHandler.format_stack/1
    (appsignal) lib/appsignal/error_handler.ex:144: Appsignal.ErrorHandler.match_error_format/2
    (appsignal) lib/appsignal/error_handler.ex:34: Appsignal.ErrorHandler.handle_event/2
    (stdlib) gen_event.erl:533: :gen_event.server_update/4
    (stdlib) gen_event.erl:515: :gen_event.server_notify/4
    (stdlib) gen_event.erl:517: :gen_event.server_notify/4
    (stdlib) gen_event.erl:256: :gen_event.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:error, #PID<0.2157.0>, {#PID<0.2194.0>, 'Ranch listener ~p had connection process started with ~p:start_link/4 at ~p exit with reason: ~999999p~n', [Betty.Endpoint.HTTP, :cowboy_protocol, #PID<0.2396.0>, {{{%Ecto.NoResultsError{message: "expected at least one result but got none in query:\n\nfrom a in Betty.Schema.Application,\n  where: a.id == ^\"2d313b9485a8447da48c29d2fd343d05\"\n"}, [{Ecto.Repo.Queryable, :one!, 4, [file: 'lib/ecto/repo/queryable.ex', line: 74]}, {Betty.App.Broker, :reload_metadata, 1, [file: 'lib/betty/app/broker.ex', line: 293]}, {Betty.App.Broker, :handle_info, 2, [file: 'lib/betty/app/broker.ex', line: 233]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 601]}, {:gen_server, :handle_msg, 5, [file: 'gen_server.erl', line: 667]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}, {GenServer, :call, [#PID<0.2398.0>, {:prepare_checkout, :web, #PID<0.2396.0>}, 5000]}}, {Betty.Endpoint, :call, [%Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{}, before_send: [], body_params: %Plug.Conn.Unfetched{aspect: :body_params}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "bookstore.betty5.dev", method: "POST", owner: #PID<0.2396.0>, params: %Plug.Conn.Unfetched{aspect: :params}, path_info: ["api", "v2", "models", "users", "records"], path_params: %{}, peer: {{127, 0, 0, 1}, 57777}, port: 4000, private: %{}, query_params: %Plug.Conn.Unfetched{aspect: :query_params}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"accept", "application/json"}, {"content-type", "application/json, application/json"}, {"authorization", "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhM2Y1NjE5OGE0ZThiMjhiMDk1N2I1MDZkMDRlZjk4ZDYzY2Q4NGI4IiwiZXhwIjoxNDg4Mzc2MzUyfQ.5JZ2T-IWAWP46eJW8X1KCalZz1_BTYeLrH-qzpNYwg8"}, {"user-agent", "hackney/1.6.6"}, {"host", "bookstore.betty5.dev:4000"}, {"content-length", "90"}], request_path: "/api/v2/models/users/records", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}], scheme: :http, script_name: [], secret_key_base: nil, state: :unset, status: nil}, []]}}]}}

```

**Comment by tombruijn** [comment]
Possibly related and same cause: #173
