### ISSUE TITLE
ErrorHandler should be more flexible

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#173]
From support:

```
2017-03-03T19:51:42.542741+00:00 app[web.1]: ** (exit) exited in: Task.await(%Task{owner: #PID<0.550.0>, pid: #PID<0.556.0>, ref: #Reference<0.0.1.3650>}, 15000)
2017-03-03T19:51:42.542742+00:00 app[web.1]: ** (EXIT) time out
2017-03-03T19:51:42.560727+00:00 app[web.1]: 11:51:42.560 [error] GenEvent handler Appsignal.ErrorHandler installed in :error_logger terminating
2017-03-03T19:51:42.560735+00:00 app[web.1]: ** (Protocol.UndefinedError) protocol Enumerable not implemented for {Task, :await, [%Task{owner: #PID<0.550.0>, pid: #PID<0.556.0>, ref: #Reference<0.0.1.3650>}, 15000]}
2017-03-03T19:51:42.560736+00:00 app[web.1]: (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
2017-03-03T19:51:42.560737+00:00 app[web.1]: (elixir) lib/enum.ex:116: Enumerable.reduce/3
2017-03-03T19:51:42.560738+00:00 app[web.1]: (elixir) lib/enum.ex:1776: Enum.reduce/3
2017-03-03T19:51:42.560739+00:00 app[web.1]: (appsignal) lib/appsignal/error_handler.ex:150: Appsignal.ErrorHandler.format_stack/1
2017-03-03T19:51:42.560740+00:00 app[web.1]: (appsignal) lib/appsignal/error_handler.ex:144: Appsignal.ErrorHandler.match_error_format/2
2017-03-03T19:51:42.560740+00:00 app[web.1]: (appsignal) lib/appsignal/error_handler.ex:34: Appsignal.ErrorHandler.handle_event/2
2017-03-03T19:51:42.560741+00:00 app[web.1]: (stdlib) gen_event.erl:533: :gen_event.server_update/4
2017-03-03T19:51:42.560742+00:00 app[web.1]: (stdlib) gen_event.erl:515: :gen_event.server_notify/4
```

Reproduced in the [timeout branch in appsignal-phoenix-example](https://github.com/jeffkreeftmeijer/appsignal-phoenix-example/tree/timeout).

**Comment by jeffkreeftmeijer** [comment]
Fixed in https://github.com/appsignal/appsignal-elixir/issues/193.
