### ISSUE TITLE
No function clause matching in Appsignal.Backtrace.remove_error_entries/1

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#192]
I get the following error while triggering a timeout error. Looks like a certain case for the backtrace errors is missing.

Found this by testing #187, but also found this to happen on `develop`.
It only happens on the first request, subsequent requests don't trigger this error.

```
mix phoenix.server
==> appsignal
Compiling 15 files (.ex)
==> appsignal_phoenix_example
Compiling 6 files (.ex)
[debug] AppSignal starting.
[info] Running AppsignalPhoenixExample.Endpoint with Cowboy using http://localhost:4000
[info] GET /timeout
[debug] Processing by AppsignalPhoenixExample.PageController.timeout/2
  Parameters: %{}
  Pipelines: [:browser]
[debug] Submitting Phoenix error AppSignal.Transaction{b7seo2cak075u}: HTTP request error: {:timeout, {Task, :await, [%Task{owner: #PID<0.578.0>, pid: #PID<0.580.0>, ref: #Reference<0.0.3.3097>}, 1]}}
[error] #PID<0.578.0> running AppsignalPhoenixExample.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /timeout
** (exit) exited in: Task.await(%Task{owner: #PID<0.578.0>, pid: #PID<0.580.0>, ref: #Reference<0.0.3.3097>}, 1)
    ** (EXIT) time out
[error] GenEvent handler Appsignal.ErrorHandler installed in :error_logger terminating
** (FunctionClauseError) no function clause matching in Appsignal.Backtrace.remove_error_entries/1
    (appsignal) lib/appsignal/backtrace.ex:24: Appsignal.Backtrace.remove_error_entries({Task, :await, [%Task{owner: #PID<0.578.0>, pid: #PID<0.580.0>, ref: #Reference<0.0.3.3097>}, 1]})
    (appsignal) lib/appsignal/backtrace.ex:19: Appsignal.Backtrace.from_stacktrace/1
    (appsignal) lib/appsignal/error_handler.ex:144: Appsignal.ErrorHandler.match_error_format/2
    (appsignal) lib/appsignal/error_handler.ex:34: Appsignal.ErrorHandler.handle_event/2
    (stdlib) gen_event.erl:533: :gen_event.server_update/4
    (stdlib) gen_event.erl:515: :gen_event.server_notify/4
    (stdlib) gen_event.erl:256: :gen_event.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:error, #PID<0.460.0>, {#PID<0.474.0>, 'Ranch listener ~p had connection process started with ~p:start_link/4 at ~p exit with reason: ~999999p~n', [AppsignalPhoenixExample.Endpoint.HTTP, :cowboy_protocol, #PID<0.578.0>, {{:timeout, {Task, :await, [%Task{owner: #PID<0.578.0>, pid: #PID<0.580.0>, ref: #Reference<0.0.3.3097>}, 1]}}, {AppsignalPhoenixExample.Endpoint, :call, [%Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{}, before_send: [], body_params: %Plug.Conn.Unfetched{aspect: :body_params}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "localhost", method: "GET", owner: #PID<0.578.0>, params: %Plug.Conn.Unfetched{aspect: :params}, path_info: ["timeout"], path_params: %{}, peer: {{127, 0, 0, 1}, 50395}, port: 4000, private: %{}, query_params: %Plug.Conn.Unfetched{aspect: :query_params}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"host", "localhost:4000"}, {"connection", "keep-alive"}, {"cache-control", "max-age=0"}, {"upgrade-insecure-requests", "1"}, {"user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36"}, {"accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"}, {"dnt", "1"}, {"referer", "http://localhost:4000/"}, {"accept-encoding", "gzip, deflate, sdch, br"}, {"accept-language", "en-US,en;q=0.8,nl;q=0.6"}], request_path: "/timeout", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}], scheme: :http, script_name: [], secret_key_base: nil, state: :unset, status: nil}, []]}}]}}
State: nil
```

**Comment by jeffkreeftmeijer** [comment]
This is a dup of https://github.com/appsignal/appsignal-elixir/issues/173, that's now throwing a different error after adding `Appsignal.Backtrace` and will be fixed by #187 and #190.
