### ISSUE TITLE
no function clause matching in Appsignal.Transaction.to_s/1

### ISSUE THREAD

**Issue by mmmries** [appsignal/appsignal-elixir#240]
I noticed an error log in my application the other day that I'm not sure how to fix. Looking through my code I don't think I passed the this map to any of the `Appsignal` APIs, I think the message is being grabbed from the metadata about a genserver crash, but then it can't be casted to a string.

Any suggestions on how to avoid this problem?

```
17:54:03.309 [error] GenServer :"CONVERSATION_-247613190" terminating
** (FunctionClauseError) no function clause matching in Appsignal.Transaction.to_s/1
    (appsignal) lib/appsignal/transaction.ex:422: Appsignal.Transaction.to_s(%{"message" => %{"chat" => %{"all_members_are_administrators" => false, "id" => 1234, "title" => "(dev) Test Translation", "type" => "group"}, "date" => 1502301242, "from" => %{"first_name" => "Joan", "id" => 1234, "language_code" => "en-US", "username" => "Joan.of.Arc"}, "message_id" => 454, "text" => "booyah!"}, "update_id" => 745225084})
    (appsignal) lib/appsignal/transaction.ex:313: Appsignal.Transaction.set_meta_data/3
    (elixir) lib/enum.ex:681: anonymous fn/3 in Enum.each/2
    (stdlib) lists.erl:1263: :lists.foldl/3
    (elixir) lib/enum.ex:1828: Enum.each/2
    (appsignal) lib/appsignal/transaction.ex:283: Appsignal.Transaction.set_meta_data/2
    (appsignal) lib/appsignal/transaction.ex:278: Appsignal.Transaction.set_meta_data/1
    (appsignal) lib/appsignal/error_handler.ex:49: Appsignal.ErrorHandler.submit_transaction/6
Last message (from Walybot.PollTelegram): {:update, %{"message" => %{"chat" => %{"all_members_are_administrators" => false, "id" => 1234, "title" => "(dev) Test Translation", "type" => "group"}, "date" => 1502301242, "from" => %{"first_name" => "Joan", "id" => 1234, "language_code" => "en-US", "username" => "Joan.of.Arc"}, "message_id" => 454, "text" => "booyah!"}, "update_id" => 745225084}}
State: %{conversation: %Walybot.Ecto.Conversation{__meta__: #Ecto.Schema.Metadata<:loaded, "conversations">, id: 2, inserted_at: ~N[2017-08-08 04:07:23.810352], name: "(dev) Test Translation", needs_translation: true, telegram_id: -247613190, updated_at: ~N[2017-08-09 17:53:58.319057]}, conversation_id: -247613190}
Client Walybot.PollTelegram is alive
    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:771: GenServer.call/3
    (walybot) lib/walybot/poll_telegram.ex:31: anonymous fn/1 in Walybot.PollTelegram.process_update/1
    (stdlib) timer.erl:166: :timer.tc/1
    (walybot) lib/walybot/poll_telegram.ex:30: Walybot.PollTelegram.process_update/1
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    (walybot) lib/telegram/bot.ex:26: Telegram.Bot.process_all_outstanding_updates/2
    (walybot) lib/walybot/poll_telegram.ex:17: Walybot.PollTelegram.handle_info/2
```

**Comment by mmmries** [comment]
Looking into this a bit further I think the problem was that I was calling `Appsignal.send_error(err, message, System.stacktrace(), %{update: %{key: "value}})`

Basically passing in a nested map of data for the context and it looks like Appsignal only supports flat maps with simple literal values for the context?

**Comment by tombruijn** [comment]
Hi @mmmries,

That's correct, we only support basic, flat, types for tags. So strings, numbers, etc. No nested values.

Tags are meant for simple values (which are/will be used to search on things). If you want to store nested data such as params, these need to be set separately on the AppSignal transaction. Something which is not possible through `send_error`. That would go something like this by manually creating a transaction:

```elixir
params = %{
  foo: %{
    bar: :baz
  }
}

transaction = Appsignal.Transaction.start(
  Appsignal.Transaction.generate_id,
  :http_request
)
|> Appsignal.Transaction.set_action("Module.function")
|> Appsignal.Transaction.set_meta_data("tag", "value")
|> Appsignal.Transaction.set_sample_data("params", params |> Appsignal.Utils.ParamsFilter.filter_values)

# Do stuff
# Set error if encounted
Appsignal.Transaction.set_error(transaction, error, message, System.stacktrace())

if Appsignal.Transaction.finish(transaction) == :sample do
   Appsignal.Transaction.set_request_metadata(transaction, conn)
end
:ok = Appsignal.Transaction.complete(transaction)
```

We'll have a look if we can handle this case better, by not raising an error.
Let me know if you need further help with this

**Comment by mmmries** [comment]
@tombruijn thanks! That makes a ton of sense. Maybe logging and error message with specifics about only accepting a shallow map of literal values would be a good first step rather than throwing an error.

Regardless, thanks for the reply. Loving appsignal so far.
