### ISSUE TITLE
Error: Poison.EncodeError at GET / expected string or atom key, got: 1

### ISSUE THREAD

**Issue by schurig** [appsignal/appsignal-elixir#25]
Since updating to `0.7.0` I'm getting the following error on every page load:

**Poison.EncodeError at GET /
expected string or atom key, got: 1**

```sh
[error] #PID<0.2361.0> running MyApp.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (Poison.EncodeError) expected string or atom key, got: 1
        (poison) lib/poison/encoder.ex:188: Poison.Encoder.Map.encode_name/1
        (poison) lib/poison/encoder.ex:212: anonymous fn/4 in Poison.Encoder.Map.encode/3
        (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
        (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map.encode/3
        (poison) lib/poison/encoder.ex:213: anonymous fn/4 in Poison.Encoder.Map.encode/3
        (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
        (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map.encode/3
        (poison) lib/poison.ex:41: Poison.encode!/2
        (appsignal) lib/appsignal/transaction.ex:189: Appsignal.Transaction.set_sample_data/3
        (appsignal) lib/appsignal/phoenix.ex:66: Appsignal.Phoenix.submit_http_error/5
        (my_app) lib/my_app/endpoint.ex:50: MyApp.Endpoint."call (overridable 2)"/2
        (my_app) lib/plug/debugger.ex:123: MyApp.Endpoint."call (overridable 3)"/2
        (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

My config

```elixir
config :appsignal, :config,
  name: :my_app,
  push_api_key: "............................",
  env: :dev,
  enable_host_metrics: true
```

**Comment by arjan** [comment]
Thanks, I'll look into it.

**Comment by arjan** [comment]
It seems that either your session data or your params contains an integer key, which Poison does not like. I'll address this.

**Comment by schurig** [comment]
Yes, there is a integer in our session data.

**Comment by arjan** [comment]
Can you test with master? If it works, I'll release a 0.7.1

**Comment by schurig** [comment]
@arjan works! :)

**Comment by arjan** [comment]
published 0.7.1

**Comment by schurig** [comment]
Thanks a lot!

**Comment by arjan** [comment]
np, thank you for reporting!
