### ISSUE TITLE
Building with docker

### ISSUE THREAD

**Issue by SjaufStefan** [appsignal/appsignal-elixir#259]
Hey guys,

I was having some issues building with docker. I've since fixed these issues and figured it would be good to post the solution here for other people who might have the same issues.

These were the errors I was getting:

_Error 1_
```
could not compile dependency :appsignal, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
** (ErlangError) Erlang error: :enoent
    (elixir) lib/system.ex:605: System.cmd("make", [], [])
    mix_helpers.exs:116: Mix.Appsignal.Helper.compile/0
    /app/deps/appsignal/mix.exs:14: Mix.Tasks.Compile.Appsignal.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/compile.all.ex:19: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:37: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
The command '/bin/sh -c MIX_ENV=prod mix do compile, release --env=prod' returned a non-zero code: 1
```

_Error 2_

```
/bin/sh: 1: cc: not found
make: *** [all] Error 127
==> appsignal
could not compile dependency :appsignal, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
** (Mix) Could not run `make`. Please check if `make` and either `clang` or `gcc` are installed

The command '/bin/sh -c MIX_ENV=prod mix do compile, release --env=prod' returned a non-zero code: 1
```

The solution to these issues is to make sure you add `build-essential` to your apt-get install command.

**Comment by jeffkreeftmeijer** [comment]
Hey @SjaufStefan! We mention `build-essential` in the [requirements part of our installation guide](https://docs.appsignal.com/elixir/installation.html#requirements), but we should add a page that links to the install guide from the Hex docs as well. Thanks for taking the time to write this down!
