### ISSUE TITLE
mix compile fails on 1.4.4

### ISSUE THREAD

**Issue by pwightman** [appsignal/appsignal-elixir#284]
I'm getting the following error after updating to 1.4.4. `mix deps.get` works fine, but `mix compile` errors with:

```
==> appsignal
could not compile dependency :appsignal, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
** (UndefinedFunctionError) function Appsignal.System.agent_platform/0 is undefined or private
    Appsignal.System.agent_platform()
    mix_helpers.exs:12: Mix.Appsignal.Helper.verify_system_architecture/0
    /Users/parkerwightman/cs/ohi/deps/appsignal/mix.exs:17: Mix.Tasks.Compile.Appsignal.run/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/compile.all.ex:19: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:37: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
```

Erlang/OTP 20
Elixir 1.4.4

**Comment by pwightman** [comment]
`mix deps.clean appsignal` fixed it, false alarm!

**Comment by jeffkreeftmeijer** [comment]
Thanks for updating us about this, @pwightman! This probably happened because you updated to a new version, and your existing compile didn't include the `Appsignal.System.agent_platform/0` function yet.
