### ISSUE TITLE
Error when compiling `:appsignal` with Docker

### ISSUE THREAD

**Issue by davidrichey** [appsignal/appsignal-elixir#388]
Elixir Version: `1.6.4`
Phoenix Version: `1.3.0`
AppSignal Version: `1.7.2`
Docker Image: `bitwalker/alpine-elixir:1.6.4 as builder`

Docker Build Output
```
Generated phoenix app

19:31:06.168 [info]  Downloading agent release from https://appsignal-agent-releases.global.ssl.fastly.net/e801925/appsignal-x86_64-linux-musl-all-static.tar.gz
==> appsignal
could not compile dependency :appsignal, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
** (ErlangError) Erlang error: :enoent
    (elixir) lib/system.ex:622: System.cmd("make", [], [])
    mix_helpers.exs:151: Mix.Appsignal.Helper.compile/0
    /app/deps/appsignal/mix.exs:11: Mix.Tasks.Compile.Appsignal.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:63: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:47: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:18: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:34: Mix.Tasks.Compile.All.with_logger_app/1
The command '/bin/sh -c mix do deps.get, deps.compile, release' returned a non-zero code: 1
```

**Comment by tombruijn** [comment]
Hi @davidrichey,

Looks like the “make” program is not available? Have you installed the required system dependencies listed in our docs https://docs.appsignal.com/support/operating-systems.html#alpine-linux
