### ISSUE TITLE
Protocol undefined when sending just an error.

### ISSUE THREAD

**Issue by CrowdHailer** [appsignal/appsignal-elixir#396]
When I try to send just a runtime error `Appsignal.send_error(%RuntimeError{})`, I get a protocol undefined error.
```
iex> Appsignal.send_error(%RuntimeError{})
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil. This protocol is implemented for: DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Postgrex.Stream, Range, Scrivener.Page, Stream, Timex.Interval
    (elixir) <truncated>/elixir/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) <truncated>/elixir/lib/elixir/lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:2979: Enum.map/2
    (appsignal) lib/appsignal/transaction.ex:209: Appsignal.Transaction.set_error/4
    (appsignal) lib/appsignal/error_handler.ex:50: Appsignal.ErrorHandler.submit_transaction/6
```

This way of sending an error is specified in the [documentation](https://github.com/appsignal/appsignal-elixir/blob/develop/lib/appsignal.ex#L142)

environment info
```
Erlang/OTP 21 [erts-10.0.6] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.7.2) - press Ctrl+C to exit (type h() ENTER for help)
```

And using appsignal `1.8.0`

**Comment by tombruijn** [comment]
Fixed in #400
