### ISSUE TITLE
Unable to compile in alpine linux

### ISSUE THREAD

**Issue by jwaldrip** [appsignal/appsignal-elixir#515]
Having difficulty compiling the app with appsignal. This was working a day ago and suddenly stopped.

## To Reproduce
`mix compile`

produces the error

```
Downloading agent release from https://appsignal-agent-releases.global.ssl.fastly.net/e1c9363/appsignal-x86_64-linux-musl-all-static.tar.gz
could not compile dependency :appsignal, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:invalid, {:error, {:error, {:option, :server_only, :honor_cipher_order}}}} of type Tuple
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
    mix_helpers.exs:515: Mix.Appsignal.Helper.write_report_file/2
    mix_helpers.exs:544: Mix.Appsignal.Helper.abort_installation/2
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:73: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:53: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:24: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
The command '/bin/sh -c mix compile --warnings-as-errors' returned a non-zero code: 1
```

- Using AppSignal for Elixir package version 1.10.12
- In my app using framework/library ... version elixir:1.9.1-alpine

**Comment by gabrielrinaldi** [comment]
@jwaldrip seems related to #512

**Comment by tombruijn** [comment]
Hi @jwaldrip, this seems like the same issue as #512. It's related to the Erlang OTP 22.1 update and an incompatibility with the hackney package. Closing this issue in favor of #512
