### ISSUE TITLE
Dialyzer warnings for version 2.0.0?

### ISSUE THREAD

**Issue by kenny-evitt** [appsignal/appsignal-elixir#589]
I created a post on Elixir Forum about some strange Dialyzer warnings I'm seeing in one project:

- [A lot of strange Dialyzer warnings after upgrading from Elixir 1.10.4 to 1.11.2 - Questions / Help - Elixir Programming Language Forum](https://elixirforum.com/t/a-lot-of-strange-dialyzer-warnings-after-upgrading-from-elixir-1-10-4-to-1-11-2/35649)

The warnings that I think *might* be related to AppSignal, in particular the new 2.0.0 version of this package, are a set of (pairs of) warnings; an example pair of warnings:

```
web/templates/merchant/freshbooks/_scripts.invoices.html.eex:1:no_return
Function _scripts.invoices.html/1 has no local return.
________________________________________________________________________________
web/templates/merchant/freshbooks/_scripts.invoices.html.eex:1:call
The function call will not succeed.
Partially.Merchant.FreshbooksView.render(
  Partially.Merchant.QuickbooksView,
  <<95, 115, 99, 114, 105, 112, 116, 115, 46, 105, 110, 118, 111, 105, 99, 101, 115, 46,
    104, 116, 109, 108>>
)
will never return since it differs in arguments with
positions 1st from the success typing arguments:
(
  binary()
  | maybe_improper_list(
      binary() | maybe_improper_list(any(), binary() | []) | char(),
      binary() | []
    ),
  any()
)
________________________________________________________________________________
```

Here’s the contents of `web/templates/merchant/freshbooks/_scripts.invoices.html.eex`:

```
<%= render Partially.Merchant.QuickbooksView, "_scripts.invoices.html" %>
```

and here’s the corresponding view (`web/views/merchant/freshbooks_view.ex`):

```
defmodule Partially.Merchant.FreshbooksView do
  use Partially.Web, :view
end
```

The `use Partially.Web, :view` itself (generates code that) calls use `Phoenix.View`.

Based on [the `Phoenix.View` source](https://github.com/phoenixframework/phoenix/blob/v1.5.6/lib/phoenix/view.ex#L155-L170) the generated `render/2` function, the template code should be handled by this clause:

```
      def render(module, template) when is_atom(module) do
        Phoenix.View.render(module, template, %{})
      end
```

I’m note sure where Dialyzer is getting the “success typing arguments”. It looks like maybe from [the `render_template/2` function(s) generated by `Phoenix.Template`](https://github.com/phoenixframework/phoenix/blob/ffd7fda72b88094106e64933edd554ea83a68aab/lib/phoenix/template.ex#L360-L362) perhaps.

Both warnings can be resolved by changing the template code to this:

```
<%= render Partially.Merchant.QuickbooksView, "_scripts.invoices.html", [] %>
```

I also just noticed [this comment](https://github.com/appsignal/appsignal-elixir/issues/319#issuecomment-642702867) (again) on issue #319:

> ... In the new version, we're moving off the template engines and added [the `Appsignal.View` module](https://github.com/appsignal/appsignal-elixir-phoenix/blob/master/lib/appsignal_phoenix/view.ex), which reimplements the `render/2` function to add instrumentation, which has been working great in our internal testing.
> 
> ...

That made me wonder whether the `Appsignal.View` re-implementation of `render/2` is causing the Dialyzer warnings.

I couldn't find the `Appsignal.View` code just now to skim it.

**Comment by axelson** [comment]
The `Appsignal.View` module code is in the appsignal-elixir-phoenix repository: https://github.com/appsignal/appsignal-elixir-phoenix/blob/f23b93798519d5403f05075dab076ebeae9214b7/lib/appsignal_phoenix/view.ex

**Comment by kenny-evitt** [comment]
@axelson Thanks!

I just realized that myself. It does look like maybe [the `render/2` function](https://github.com/appsignal/appsignal-elixir-phoenix/blob/2.0.0/lib/appsignal_phoenix/view.ex#L48-L57) generated by `Appsignal.Phoenix.View` might be what Dialyzer is finding for its "success typing":

```elixir
      def render(template, assigns) do
        {root, _pattern, _names} = __templates__()
        path = Path.join(root, template)

        Appsignal.instrument("Render #{path}", fn span ->
          @span.set_attribute(span, "title", path)
          @span.set_attribute(span, "appsignal:category", "render.phoenix_template")
          super(template, assigns)
        end)
      end
```

It looks like maybe the success typing is coming from `Path.join/2`; it's spec:

```elixir
@spec join(t, t) :: binary
```

Where `t()` is:

```elixir
t() :: IO.chardata()
```

And `IO.chardata()` is:

```elixir
chardata() ::
  String.t() | maybe_improper_list(char() | chardata(), String.t() | [])
```

**Comment by kenny-evitt** [comment]
@jeffkreeftmeijer Maybe `Appsignal.Phoenix.View` should be 'overriding' all of the function clauses for [the `render/2` function generated by `Phoenix.View](https://github.com/phoenixframework/phoenix/blob/v1.5.6/lib/phoenix/view.ex#L155-L170)?

I think maybe the AppSignal override is hiding this clause in particular, which is what my code was expecting to call:

```elixir
      def render(module, template) when is_atom(module) do
        Phoenix.View.render(module, template, %{})
      end
```

**Comment by kenny-evitt** [comment]
I'm seeing another set of warnings that I *suspect* might be related to the first set; an example:

```
web/views/admin/affiliate_view.ex:2:guard_fail
The guard test:

is_atom(
  _ ::
    binary()
    | maybe_improper_list(
        binary() | maybe_improper_list(any(), binary() | []) | char(),
        binary() | []
      )
)

can never succeed.

```

The file `web/views/admin/affiliate_view.ex`:

```elixir
defmodule Partially.Admin.AffiliateView do
    use Partially.Web, :view
end
```

`Partially.Web.__using__/1`:

```elixir
  @doc """
  When used, dispatch to the appropriate controller/view/etc.
  """
  defmacro __using__(which) when is_atom(which) do
    apply(__MODULE__, which, [])
  end
```

I did think it odd that a guard was being used with a macro – I couldn't find any info about whether that *is* allowed (or not) and couldn't find anything in a few cursory web searches. (That seemed to be mostly because results for 'elixir macro guard' were mostly about generating functions with guards using macros.)

Or maybe Dialyzer is complaining about some specific code generated by `use Partially.Web, :view`?

That generated code includes, first:

```elixir
      use Phoenix.View, root: "web/templates"

      use Appsignal.Phoenix.View

      ...
```

The success typing in the warning does look (somewhat suspiciously) the same as in the warnings for the `render/2` calls.

**Comment by jeffkreeftmeijer** [comment]
Hey @kenny-evitt,

I've been looking at these, and I think I fixed most warnings we see in standard Phoenix apps. We're reviewing the patches internally, but it'd be great if you could run them locally to see if they also fix your issues.

``` elixir
 {:appsignal_phoenix, github: "appsignal/appsignal-elixir-phoenix"},
 {:appsignal_plug, github: "appsignal/appsignal-elixir-plug", override: true},
 {:appsignal, github: "appsignal/appsignal-elixir", override: true}, 
```

If not, could you post a new list of issues your app generates?

**Comment by kenny-evitt** [comment]
@jeffkreeftmeijer – hey! Thanks for your help with this.

I edited/added the deps in `mix.exs` to match what you mentioned.

I ran these commands first:

```
$ mix clean
$ mix deps.clean --all --build
$ mix deps.get
```

`mix compile` failed.

<details><summary>The full output:</summary><p>

```
$ mix compile
...
warning: Jason.decode/1 defined in application :jason is used by the current application but the current application does not directly depend on :jason. To fix this, you must do one of:

  1. If :jason is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :jason is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :jason, you may optionally skip this warning by adding [xref: [exclude: Jason]] to your "def project" in mix.exs

  lib/appsignal/json.ex:30: Appsignal.Json.decode/1

warning: Jason.decode!/1 defined in application :jason is used by the current application but the current application does not directly depend on :jason. To fix this, you must do one of:

  1. If :jason is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :jason is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :jason, you may optionally skip this warning by adding [xref: [exclude: Jason]] to your "def project" in mix.exs

  lib/appsignal/json.ex:31: Appsignal.Json.decode!/1

warning: Jason.encode/1 defined in application :jason is used by the current application but the current application does not directly depend on :jason. To fix this, you must do one of:

  1. If :jason is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :jason is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :jason, you may optionally skip this warning by adding [xref: [exclude: Jason]] to your "def project" in mix.exs

  lib/appsignal/json.ex:28: Appsignal.Json.encode/1

warning: Jason.encode!/1 defined in application :jason is used by the current application but the current application does not directly depend on :jason. To fix this, you must do one of:

  1. If :jason is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :jason is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :jason, you may optionally skip this warning by adding [xref: [exclude: Jason]] to your "def project" in mix.exs

  lib/appsignal/json.ex:29: Appsignal.Json.encode!/1

warning: Phoenix.Template.EExEngine.compile/2 defined in application :phoenix is used by the current application but the current application does not directly depend on :phoenix. To fix this, you must do one of:

  1. If :phoenix is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :phoenix is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :phoenix, you may optionally skip this warning by adding [xref: [exclude: Phoenix.Template.EExEngine]] to your "def project" in mix.exs

  lib/appsignal/phoenix/template/eex_engine.ex:11: Appsignal.Phoenix.Template.EExEngine.compile/2

warning: Phoenix.Template.ExsEngine.compile/2 defined in application :phoenix is used by the current application but the current application does not directly depend on :phoenix. To fix this, you must do one of:

  1. If :phoenix is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :phoenix is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :phoenix, you may optionally skip this warning by adding [xref: [exclude: Phoenix.Template.ExsEngine]] to your "def project" in mix.exs

  lib/appsignal/phoenix/template/exs_engine.ex:11: Appsignal.Phoenix.Template.ExsEngine.compile/2

warning: Plug.Conn.fetch_query_params/1 defined in application :plug is used by the current application but the current application does not directly depend on :plug. To fix this, you must do one of:

  1. If :plug is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :plug is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :plug, you may optionally skip this warning by adding [xref: [exclude: Plug.Conn]] to your "def project" in mix.exs

  lib/appsignal/transaction.ex:506: Appsignal.Transaction.set_request_metadata/2

warning: Plug.Conn.get_resp_header/2 defined in application :plug is used by the current application but the current application does not directly depend on :plug. To fix this, you must do one of:

  1. If :plug is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :plug is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :plug, you may optionally skip this warning by adding [xref: [exclude: Plug.Conn]] to your "def project" in mix.exs

  lib/appsignal/plug.ex:158: Appsignal.Plug.extract_meta_data/1

warning: :telemetry.attach_many/4 defined in application :telemetry is used by the current application but the current application does not directly depend on :telemetry. To fix this, you must do one of:

  1. If :telemetry is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :telemetry is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :telemetry, you may optionally skip this warning by adding [xref: [exclude: :telemetry]] to your "def project" in mix.exs

  lib/appsignal/phoenix/event_handler.ex:10: Appsignal.Phoenix.EventHandler.attach/0

warning: Supervisor.Spec.worker/2 is deprecated. Use the new child specifications outlined in the Supervisor module instead
  lib/appsignal.ex:46: Appsignal.start/2

warning: Supervisor.Spec.worker/3 is deprecated. Use the new child specifications outlined in the Supervisor module instead
Found at 2 locations:
  lib/appsignal.ex:44: Appsignal.start/2
  lib/appsignal.ex:45: Appsignal.start/2

Generated appsignal app
==> appsignal_plug
Compiling 2 files (.ex)
warning: redefining module Appsignal.Plug (current version loaded from /Users/kenny/@code/partially_ex/_build/dev/lib/appsignal/ebin/Elixir.Appsignal.Plug.beam)
  lib/appsignal_plug.ex:1


== Compilation error in file lib/appsignal_plug/metadata.ex ==
** (ArgumentError) Appsignal.Metadata is not available
    (elixir 1.11.2) lib/protocol.ex:316: Protocol.assert_protocol!/2
    lib/appsignal_plug/metadata.ex:1: (file)
    (elixir 1.11.2) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
could not compile dependency :appsignal_plug, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal_plug", update it with "mix deps.update appsignal_plug" or clean it with "mix deps.clean appsignal_plug"
```

</p></details>

Some of those warnings look like they're due to an Elixir change. I've seen similar errors for other apps as well as our own but don't yet know what to make of them.

Running `mix compile` again results in the same error:

```
$ mix compile
==> appsignal_plug
Compiling 2 files (.ex)

...
warning: redefining module Appsignal.Plug (current version loaded from /Users/kenny/@code/partially_ex/_build/dev/lib/appsignal/ebin/Elixir.Appsignal.Plug.beam)
  lib/appsignal_plug.ex:1


== Compilation error in file lib/appsignal_plug/metadata.ex ==
** (ArgumentError) Appsignal.Metadata is not available
    (elixir 1.11.2) lib/protocol.ex:316: Protocol.assert_protocol!/2
    lib/appsignal_plug/metadata.ex:1: (file)
    (elixir 1.11.2) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
could not compile dependency :appsignal_plug, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal_plug", update it with "mix deps.update appsignal_plug" or clean it with "mix deps.clean appsignal_plug"
```

**Comment by jeffkreeftmeijer** [comment]
Hey @kenny-evitt,

Thanks for helping us test this! There are two things we’ll need to check to make sure we’re talking about the same thing. First off, could you double-check your dependencies? I’ve updated the sample I posted, as the original post didn’t include the branch names:

```
{:appsignal_phoenix, github: "appsignal/appsignal-elixir-phoenix", branch: "unmatched-returns"},
{:appsignal_plug, github: "appsignal/appsignal-elixir-plug", branch: "unmatched-returns", override: true},
{:appsignal, github: "appsignal/appsignal-elixir", branch: "unmatched-returns", override: true}
```

Secondly, could you check if you have `:jason` included as part of your dependencies in your Phoenix app?

```
{:jason, "~> 1.0”}
```

We should throw a warning if it doesn’t exist, so the Jason dependency not being there shouldn’t break compilation. I’ll investigate some more, and will open a new issue with my findings on that.

**Comment by jeffkreeftmeijer** [comment]
Closing this. We’ve merged https://github.com/appsignal/appsignal-elixir/pull/593, which solves the issue in our testing setup. Please reopen if you’re still running into this issue!

**Comment by kenny-evitt** [comment]
I'm not seeing any of these errors, or any errors, now, with a more recent version of the Hex packages.

Thanks for your help!
