### ISSUE TITLE
Failure with error reporting

### ISSUE THREAD

**Issue by rranelli** [appsignal/appsignal-elixir#6]
I'm trying to get error reporting to work on a trial account. I've written a very simple controller:

```
def MyApp.HomeController do
  def boom(_, _) do
    IO.puts " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    raise "AEHOOOOOO"
  end
end
```

and in the `endpoint.ex`:

```
defmodule MyApp.Endpoint do
  use Phoenix.Endpoint, otp_app: :lukla_web
  use Appsignal.Phoenix
# ...
end
```

When calling this action, I get the following in the console:

```
17:28:34.661 request_id=1e9odipejcgj3vijf08kgs3c812gfnc6 [info] Sent 500 in 10ms
17:28:34.663 [debug] Submitting AppSignal.Transaction{oesu2asj4c1m8}: HTTP request #PID<0.871.0> crashed
Server: localhost:4000 (http)
Request: GET /boom
** (exit) an exception was raised:
    ** (RuntimeError) AEHOOOOOO
        (my_app) web/controllers/home_controller.ex:54: MyApp.HomeController.exploda/2
        (my_app) web/controllers/home_controller.ex:1: MyApp.HomeController.action/2
        (my_app) web/controllers/home_controller.ex:1: MyApp.HomeController.phoenix_controller_pipeline/2
        (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.instrument/4
        (my_app) lib/phoenix/router.ex:261: MyApp.Router.dispatch/2
        (my_app) web/router.ex:1: MyApp.Router.do_call/2
        (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.phoenix_pipeline/1
        (my_app) lib/my_app/endpoint.ex:3: MyApp.Endpoint."call (overridable 2)"/2
```

How should I debug this? I'm sure the process is sending stuff over to `push.appsignal.com` I tcp dump'd it, but nothing shows up on the error interface @ appsignal.com

What should I do?

**Comment by arjan** [comment]
Thanks for the detailed report. If you're sure that the request is being sent, @thijsc should be the one to help you, I guess.

**Comment by thijsc** [comment]
Could you send the full output of appsignal.log to support@appsignal.com?

**Comment by arjan** [comment]
Closing, as this does not look like a bug in the Elixir library.
