### ISSUE TITLE
Installation fails on Apple Silicon

### ISSUE THREAD

**Issue by crbelaus** [appsignal/appsignal-elixir#615]
## Describe the bug

(Not sure if this should be reported here)

AppSignal fails to install in Apple Silicon.

I am running a M1 Macbook Air and when building the project the installation fails and the integration is disabled, although the pacakge compiles properly

## To Reproduce

- Erlang 23.1.1 and Elixir 1.11.1 both running native in ARM
- Using AppSignal for Elixir package version 2.0.6
- Using AppSignal for Phoenix pacakge version 2.0.3
- Using AppSignal for Plug package version 2.0.4

Creating a project with AppSignal and running `mix deps.get` throws the following error:

```
==> appsignal
AppSignal installation failed: Unknown target platform arm-apple-darwin20.2.0 - darwin, AppSignal integration disabled!
Please check http://docs.appsignal.com/support/operating-systems.html
Compiling 42 files (.ex)
Generated appsignal app
```

**Comment by jeffkreeftmeijer** [comment]
Hey @crbelaus,

Thanks for testing this out. Could you run our [diagnose command](https://docs.appsignal.com/elixir/command-line/diagnose.html) in your project (`mix appsignal.diagnose --send-report`)? That should send us the install log with the information we need to start debugging this. Thanks!

**Comment by crbelaus** [comment]
Hi @jeffkreeftmeijer! I've just run the diagnose command and this is the output:

<details>
<summary>mix appsignal.diagnose --send-report</summary>

```
mix appsignal.diagnose --send-report
warning: Error loading NIF (Is your operating system (arm-apple-darwin20.2.0) supported? Please check http://docs.appsignal.com/support/operating-systems.html):
Failed to load NIF library: 'dlopen(/Users/crbelaus/Projects/hcmex/_build/dev/lib/appsignal/priv/appsignal_extension.so, 2): image not found'
  (appsignal 2.0.6) lib/appsignal/nif.ex:23: Appsignal.Nif.init/0
  (kernel 7.1) code_server.erl:1355: anonymous fn/1 in :code_server.handle_on_load/5

AppSignal diagnose
================================================================================
Use this information to debug your configuration.
More information is available on the documentation site.
http://docs.appsignal.com/
Send this output to support@appsignal.com if you need help.
================================================================================

AppSignal agent
  Language: Elixir
  Package version: 2.0.6
  Agent version: 
  Nif loaded: no

Extension installation report
  Installation result
    Status: "failed"
    Message: "Unknown target platform arm-apple-darwin20.2.0 - darwin, AppSignal integration disabled!\nPlease check http://docs.appsignal.com/support/operating-systems.html"
  Language details
    Elixir version: "1.11.1"
    OTP version: "23"
  Error found while parsing the download report.
  Error: :enoent
  Build details
    Install time: "2021-01-05T14:36:52.280892Z"
    Source: nil
    Agent version: nil
    Architecture: 'arm-apple-darwin20.2.0'
    Target: "darwin"
    Musl override: false
    Library type: "static"
  Host details
    Root user: false
    Dependencies: %{}

Host information
  Architecture: arm-apple-darwin20.2.0
  Elixir version: 1.11.1
  OTP version: 23
  Operating System: darwin
  root user: no
  Container: no

Agent diagnostics
  Error: Nif not loaded, aborting.

Configuration
  active: false
    Sources:
      default: false
      file:    false
  ca_file_path: "/Users/crbelaus/Projects/hcmex/_build/dev/lib/appsignal/priv/cacert.pem"
  debug: false
  diagnose_endpoint: "https://appsignal.com/diag"
  dns_servers: []
  enable_host_metrics: true
  enable_minutely_probes: true
  endpoint: "https://push.appsignal.com"
  env: :dev
  files_world_accessible: true
  filter_data_keys: []
  filter_parameters: []
  filter_session_data: []
  ignore_actions: ["HcmexWeb.StatusController#show"]
    Sources:
      default: []
      file:    ["HcmexWeb.StatusController#show"]
  ignore_errors: ["Bodyguard.NotAuthorizedError", "Phoenix.Router.NoRouteError"]
    Sources:
      default: []
      file:    ["Bodyguard.NotAuthorizedError", "Phoenix.Router.NoRouteError"]
  ignore_namespaces: []
  log: "file"
  name: "hcmex" (Loaded from file)
  otp_app: :hcmex (Loaded from file)
  request_headers: ["accept", "accept-charset", "accept-encoding", "accept-language", "cache-control", "connection", "content-length", "path-info", "range", "request-method", "request-uri", "server-name", "server-port", "server-protocol", "referer", "x-forwarded-for"]
    Sources:
      default: ["accept", "accept-charset", "accept-encoding", "accept-language", "cache-control", "connection", "content-length", "path-info", "range", "request-method", "request-uri", "server-name", "server-port", "server-protocol"]
      file:    ["accept", "accept-charset", "accept-encoding", "accept-language", "cache-control", "connection", "content-length", "path-info", "range", "request-method", "request-uri", "server-name", "server-port", "server-protocol", "referer", "x-forwarded-for"]
  running_in_container: true (Loaded from file)
  send_params: true
  skip_session_data: false
  transaction_debug_mode: false
  valid: false

Read more about how the diagnose config output is rendered
https://docs.appsignal.com/elixir/command-line/diagnose.html

Validation
  Push API key: invalid

Paths
  AppSignal log
    Path: "/tmp/appsignal.log"
    Exists?: no
  Log directory
    Path: "/tmp"
    Writable?: yes
    Ownership?: no (file: 0, process: 501)
  Working directory
    Path: "/Users/crbelaus/Projects/hcmex"
    Writable?: yes
    Ownership?: yes (file: 501, process: 501)


Diagnostics report
  Do you want to send this diagnostics report to AppSignal?
  If you share this report you will be given a link to 
  AppSignal.com to validate the report.
  You can also contact us at support@appsignal.com
  with your support token.


  Confirmed sending report using --send-report option.

  Transmitting diagnostics report
  Your support token: diagffa063d48e8701f9156d
  View this report:   https://appsignal.com/diagnose/diagffa063d48e8701f9156d
```
</details>

**Comment by jeffkreeftmeijer** [comment]
Thanks! That makes sense, as we can’t start the diagnose command if the Nif wasn’t compiled. Could you check if you have an install.log file? It should be in `_build/dev/lib/appsignal/priv/install.report`.

**Comment by crbelaus** [comment]
Of course! This is the install log

<details>
<summary>_build/dev/lib/appsignal/priv/install.report (formatted so it is easier to read)</summary>

```json
{
  "build": {
    "architecture": [97,114,109,45,97,112,112,108,101,45,100,97,114,119,105,110,50,48,46,50,46,48],
    "library_type": "static",
    "musl_override": false,
    "package_path": "/Users/crbelaus/Projects/hcmex/_build/dev/lib/appsignal/priv",
    "target": "darwin",
    "time": "2021-01-06T10:21:13.685856Z"
  },
  "host": {
    "dependencies": {},
    "root_user": false
  },
  "language": {
    "name": "elixir",
    "otp_version": "23",
    "version": "1.11.1"
  },
  "result": {
    "message": "Unknown target platform arm-apple-darwin20.2.0 - darwin, AppSignal integration disabled!\nPlease check http://docs.appsignal.com/support/operating-systems.html",
    "status": "failed"
  }
}
```
</details>

**Comment by tombruijn** [comment]
I've updated our supported operating systems docs page (https://docs.appsignal.com/support/operating-systems.html) to mention we do not currently support Apple Silicon for our extension and agent.

We will need to compile and release a special build to support this. We currently have no machine for this. For now we recommend running the app and AppSignal through Rosetta 2 on macOS if you do need to run AppSignal. We'll update here when there are updates around support for this.

**Comment by atonse** [comment]
Could this possibly help? bcrypt_elixir just wasn't putting the nif in the right place. I suspect it's something like that?

https://github.com/riverrun/bcrypt_elixir/issues/29

I have moved to an M1 mac mini as my main dev machine. If you want me to test any beta code compiling on my machine, please let me know. This isn't hurting us right now since all our servers are Intel, but would be nice to add support at some point.

**Comment by tombruijn** [comment]
It will require a bit more work for us as we need to compile our agent and extension for arm64 as well. Similar changes may need to be made in the Makefile.

For now, if you need AppSignal on M1 machines, we recommend running it under rosetta2.

**Comment by cblavier** [comment]
interested as well!

**Comment by atonse** [comment]
Right now the rest of our elixir app works just fine under the M1 (using arm-compiled elixir) so i'm ok with AppSignal just failing. Hopefully this gets fixed soon enough but I understand if there is a learning curve involved.

**Comment by nubeiro** [comment]
Any hints on how to run appsignal through Rosetta 2?

**Comment by tombruijn** [comment]
Prefix an app command with this: `arch -x86_64 mix ...`
Or run your entire shell this way: `arch -x86_64 zsh`

You can also configure an alternative terminal app like iTerm2 to run entirely under rosetta2. Any app that you run in that terminal will be running under rosetta2 then.

Go to Finder > Applications > Your terminal app of choice > right click > "Get info" context menu item. Then in the App info window, check "Open using Rosetta". Restart the terminal app.
[Apple help page about this](https://support.apple.com/en-us/HT211861)

**Comment by tombruijn** [comment]
Experimental support has been added for this in the latest 2.1.11 release of the Elixir package. Please let us know if it works here, or at support@appsignal.com with a [diagnose report](https://docs.appsignal.com/elixir/command-line/diagnose.html).

Closing the issue now. We can reopen it if new issues arise.

**Comment by crbelaus** [comment]
@tombruijn I can confirm that the 2.1.11 release works perfect in a Macbook Air M1 🚀

**Comment by tombruijn** [comment]
@crbelaus That's great to hear! 🎉 🍰

**Comment by felipero** [comment]
I got an error with 2.1.15. Here's the install log: 
```json
{
  "build": {
    "agent_version": "0f40689",
    "architecture": "aarch64",
    "library_type": "static",
    "linux_arm_override": false,
    "musl_override": false,
    "package_path": "/Users/felipero/workspace/omella/backend/_build/dev/lib/appsignal/priv",
    "source": "cached_in_tmp_dir",
    "target": "darwin",
    "time": "2021-08-17T17:54:46.115000Z"
  },
  "download": {
    "checksum": "verified",
    "download_url": "https://appsignal-agent-releases.global.ssl.fastly.net/0f40689/appsignal-aarch64-darwin-all-static.tar.gz"
  },
  "host": { "dependencies": {}, "root_user": false },
  "language": { "name": "elixir", "otp_version": "24", "version": "1.12.0" },
  "result": {
    "message": "Build error was encountered while running `make` (exit code: 2):\n\nc_src/appsignal_extension.c:1141:21: warning: unused function '_set_span_attribute_sql_string' [-Wunused-function]\nstatic ERL_NIF_TERM _set_span_attribute_sql_string(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[])\n                    ^\n1 warning generated.\nld: warning: ignoring file /Users/felipero/workspace/omella/backend/_build/dev/lib/appsignal/priv/libappsignal.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64\nld: fatal warning(s) induced error (-fatal_warnings)\nclang: error: linker command failed with exit code 1 (use -v to see invocation)\nmake: *** [all] Error 1\n\n",
    "status": "failed"
  }
}
```

**Comment by felipero** [comment]
Also from time to time I get this, when running iex for example:
```
warning: Error loading NIF (Is your operating system (aarch64-apple-darwin20.5.0) supported? Please check http://docs.appsignal.com/support/operating-systems.html):
Failed to load NIF library: 'dlopen(/Users/felipero/workspace/omella/backend/_build/dev/lib/appsignal/priv/appsignal_extension.so, 2): image not found'
  (appsignal 2.1.15) lib/appsignal/nif.ex:23: Appsignal.Nif.init/0
  (kernel 8.0.2) code_server.erl:1317: anonymous fn/1 in :code_server.handle_on_load/5
```

**Comment by tombruijn** [comment]
Your first error is probably because it previously downloaded the x86_64 architecture and somehow reused that for the new install. I'm basing that on that it says `"source": "cached_in_tmp_dir"`. Removing the `_build` dir would fix that.

It may also help to start from fresh entirely, remove the `deps` and `_build` dirs, but also any "appsignal" files in the `/tmp` dir on the host. Maybe something is out of date or using old installs still.

**Comment by felipero** [comment]
Great. Removing `/tmp/appsignal-agent-0f40689.tar.gz` did the trick. Thanks @tombruijn

**Comment by felipero** [comment]
Actually, odd enough, I just got the warning today again. Is there anything else I could do to fix that?
```
warning: Error loading NIF (Is your operating system (aarch64-apple-darwin20.5.0) supported? Please check http://docs.appsignal.com/support/operating-systems.html):
Failed to load NIF library: 'dlopen(/Users/felipero/workspace/omella/backend/_build/dev/lib/appsignal/priv/appsignal_extension.so, 2): image not found'
  (appsignal 2.1.15) lib/appsignal/nif.ex:23: Appsignal.Nif.init/0
  (kernel 8.0.2) code_server.erl:1317: anonymous fn/1 in :code_server.handle_on_load/5
```

**Comment by tombruijn** [comment]
@felipero I hope more information will be available in the diagnose report. Can you send that to support@appsignal.com?

**Comment by nickgnd** [comment]
I experienced the same issue reported by @felipero 

```
warning: Error loading NIF (Is your operating system (aarch64-apple-darwin) supported? Please check http://docs.appsignal.com/support/operating-systems.html):
Failed to load NIF library: 'dlopen(/Users/nico/code/project/project_webapps/_build/dev/lib/appsignal/priv/appsignal_extension.so, 0x0002): tried: '/Users/nico/code/project/project_webapps/_build/dev/lib/appsignal/priv/appsignal_extension.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/nico/code/project/project_webapps/_build/dev/lib/appsignal/priv/appsignal_extension.so' (no such file), '/Users/nico/code/project/project_webapps/_build/dev/lib/appsignal/priv/appsignal_extension.so' (no such file), '/Users/nico/code/project/project_webapps/deps/appsignal/priv/appsignal_extension.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/nico/code/project/project_webapps/deps/appsignal/priv/appsignal_extension.so' (no such file), '/Users/nico/code/project/project_webapps/deps/appsignal/priv/appsignal_extension.so' (no such file)'
  (appsignal 2.13.4) lib/appsignal/nif.ex:23: Appsignal.Nif.init/0
  (kernel 10.2) code_server.erl:1379: anonymous fn/1 in :code_server.schedule_on_load/4
```

Deleting the `_build` folder and running `mix compile` "fixed" it for me (no more warning).

Hope it helps ✌ 

---

My system:

- Apple M3 Pro
- Sequoia 15.3.1
- Erlang/OTP 27
- Elixir 1.18.2 (compiled with Erlang/OTP 27)
- appsignal v2.13.4
