### ISSUE TITLE
Release v2.2.1 is broken when appsignal-agent is found in tmp cache

### ISSUE THREAD

**Issue by bitwalker** [appsignal/appsignal-elixir#672]
In `mix_helpers.exs`, when the download of the agent is skipped because it is found in a tmp directory, the code which writes the compilation report expects a `download_url` key to be in the `download` portion of the map, but it is omitted when using the cached agent, causing compilation of the dependency to fail due to a match error.

It can probably be fixed simply by making `download_url` be the local file path, either that or changing the `write_report` function to not match on that.

```elixir
❯ mix compile
===> Analyzing applications...
===> Compiling parse_trans
===> Analyzing applications...
===> Compiling mimerl
==> decorator
Compiling 2 files (.ex)
Generated decorator app
===> Analyzing applications...
===> Compiling metrics
===> Analyzing applications...
===> Compiling unicode_util_compat
===> Analyzing applications...
===> Compiling idna
===> Analyzing applications...
===> Compiling telemetry
==> jason
Compiling 8 files (.ex)
Generated jason app
==> ssl_verify_fun
Compiling 7 files (.erl)
Generated ssl_verify_fun app
===> Analyzing applications...
===> Compiling certifi
===> Analyzing applications...
===> Compiling hackney
==> appsignal
AppSignal extension installation successful
could not compile dependency :appsignal, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
** (MatchError) no match of right hand side value: %{build: %{agent_version: "0318770", architecture: "x86_64", library_type: "static", linux_arm_override: false, musl_override: false, package_path: "/code/src/github.com/appsignal/test/_build/dev/lib/appsignal/priv", source: "cached_in_tmp_dir", target: "darwin", time: "2021-09-03T13:31:34.215877Z"}, download: %{checksum: "verified"}, host: %{dependencies: %{}, root_user: false}, language: %{name: "elixir", otp_version: "24", version: "1.12.1"}, result: %{status: :success}}
    mix_helpers.exs:516: Mix.Appsignal.Helper.write_download_report/1
    mix_helpers.exs:495: Mix.Appsignal.Helper.write_report/1
    mix_helpers.exs:248: Mix.Appsignal.Helper.compile/1
    mix_helpers.exs:27: Mix.Appsignal.Helper.install/0
    /code/src/github.com/appsignal/test/deps/appsignal/mix.exs:6: Mix.Tasks.Compile.Appsignal.run/1
    (mix 1.12.1) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.1) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.12.1) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
```

**Comment by tombruijn** [comment]
Thanks for reporting @bitwalker! I haven't seen this happen before, but we'll take a look.

**Comment by bitwalker** [comment]
@tombruijn Any update on this? The release is broken if the cache is hit, at a minimum you should probably retire the 2.2.1 release until you all get a chance to look further. I just had it fail on another project after updating deps.

**Comment by tombruijn** [comment]
@bitwalker No fix just yet, but we'll work on it more today to get it fixed.

**Comment by tombruijn** [comment]
I've made a PR with a fix in #674

**Comment by tombruijn** [comment]
@bitwalker I've published a new version that should fix the issue. Can you confirm it works for you now?

**Comment by bitwalker** [comment]
That seems to have done it @tombruijn. Thanks!

**Comment by tombruijn** [comment]
Awesome! Thanks for reporting back @bitwalker  😄
