### ISSUE TITLE
Bump credo version

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#691]
We're using an older version of credo that doesn't run on newer versions of Elixir anymore.

Can we upgrade to a newer version of credo? What Elixir versions does that newer version of credo support?

If we upgrade, we need to upgrade all Elixir integration repos.

## The error

```
$ mix credo --strict

Error while running Elixir.Credo.Check.Consistency.SpaceAroundOperators

16:41:44.863 [error] Task #PID<0.3248.0> started from #PID<0.94.0> terminating
** (FunctionClauseError) no function clause matching in Credo.Code.Token.PositionHelper.position/1
    (credo 1.0.5) lib/credo/code/token.ex:49: Credo.Code.Token.PositionHelper.position({:sigil, {275, 17, nil}, 119, ["\n          ExampleApplication.PageController#ignored\n          ExampleApplication.PageController#also_ignored\n      "], [], nil, "("})
    (credo 1.0.5) lib/credo/check/consistency/space_around_operators/space_helper.ex:53: Credo.Check.Consistency.SpaceAroundOperators.SpaceHelper.no_space_between?/2
    (credo 1.0.5) lib/credo/check/consistency/space_around_operators/collector.ex:166: Credo.Check.Consistency.SpaceAroundOperators.Collector.without_space?/3
    (credo 1.0.5) lib/credo/check/consistency/space_around_operators/collector.ex:130: Credo.Check.Consistency.SpaceAroundOperators.Collector.record_spaces/4
    (credo 1.0.5) lib/credo/check/consistency/space_around_operators/collector.ex:37: Credo.Check.Consistency.SpaceAroundOperators.Collector.traverse_tokens/3
    (credo 1.0.5) lib/credo/check/consistency/collector.ex:140: anonymous fn/3 in Credo.Check.Consistency.Collector.find_issues/4
    (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
Function: #Function<10.99347140/0 in Credo.Check.Runner.run/2>
    Args: []
```

**Comment by unflxw** [comment]
Answering the following questions that I'd missed when working on this task:

> Can we upgrade to a newer version of credo? What Elixir versions does that newer version of credo support?

Yes, we can. I have verified that the newest version of credo (`1.5.6`) works correctly from Elixir 1.7 onwards.

> If we upgrade, we need to upgrade all Elixir integration repos.

`appsignal-elixir-phoenix` and `appsignal-elixir-plug` had their dependency set as `~> 1.4`, which would pick the highest `1.x` available, so they were already using `1.5.6`.
